import type { BlockId } from "../types/blockId";
import type { BlockMaterial } from "../types/minecraftBlock";

export const BLOCK_MATERIALS: Record<BlockId, BlockMaterial[]> = {
  "acacia_log": ["wood"],
  "acacia_log_top": ["wood"],
  "acacia_planks": ["wood"],
  "andesite": ["natural_stone", "stone"],
  "bamboo_block": ["bamboo", "wood"],
  "bamboo_mosaic": ["bamboo", "wood"],
  "bamboo_planks": ["bamboo", "wood"],
  "birch_log": ["wood"],
  "birch_log_top": ["wood"],
  "birch_planks": ["wood"],
  "black_concrete": ["concrete"],
  "black_concrete_powder": ["concrete"],
  "black_glazed_terracotta": ["terracotta"],
  "black_terracotta": ["terracotta"],
  "black_wool": ["wool_and_carpet"],
  "blackstone": ["blackstone", "nether", "stone"],
  "blue_concrete": ["concrete"],
  "blue_concrete_powder": ["concrete"],
  "blue_glazed_terracotta": ["terracotta"],
  "blue_terracotta": ["terracotta"],
  "blue_wool": ["wool_and_carpet"],
  "bricks": ["masonry", "stone"],
  "brown_concrete": ["concrete"],
  "brown_concrete_powder": ["concrete"],
  "brown_glazed_terracotta": ["terracotta"],
  "brown_terracotta": ["terracotta"],
  "brown_wool": ["wool_and_carpet"],
  "calcite": ["natural_stone", "stone"],
  "cherry_log": ["wood"],
  "cherry_log_top": ["wood"],
  "cherry_planks": ["wood"],
  "chiseled_deepslate": ["deepslate", "masonry", "stone"],
  "chiseled_nether_bricks": ["masonry", "nether", "nether_brick", "stone"],
  "chiseled_polished_blackstone": ["blackstone", "masonry", "stone"],
  "chiseled_quartz_block": ["masonry", "quartz", "stone"],
  "chiseled_resin_bricks": ["masonry", "resin", "stone"],
  "chiseled_stone_bricks": ["masonry", "stone"],
  "chiseled_tuff": ["masonry", "stone", "tuff"],
  "chiseled_tuff_bricks": ["masonry", "stone", "tuff"],
  "clay": ["earth"],
  "coal_block": ["metal_and_ore"],
  "cobbled_deepslate": ["deepslate", "masonry", "natural_stone", "stone"],
  "cobblestone": ["stone"],
  "cracked_deepslate_bricks": ["deepslate", "masonry", "stone"],
  "cracked_deepslate_tiles": ["deepslate", "masonry", "stone"],
  "cracked_nether_bricks": ["masonry", "nether", "nether_brick", "stone"],
  "cracked_polished_blackstone_bricks": ["blackstone", "masonry", "stone"],
  "cracked_stone_bricks": ["masonry", "stone"],
  "creaking_heart": ["resin", "stone"],
  "crimson_nylium": ["nether", "organics"],
  "crimson_planks": ["nether", "nether_wood", "wood"],
  "cyan_concrete": ["concrete"],
  "cyan_concrete_powder": ["concrete"],
  "cyan_glazed_terracotta": ["terracotta"],
  "cyan_terracotta": ["terracotta"],
  "cyan_wool": ["wool_and_carpet"],
  "dark_oak_log": ["wood"],
  "dark_oak_log_top": ["wood"],
  "dark_oak_planks": ["wood"],
  "dark_prismarine": ["prismarine", "stone"],
  "deepslate": ["deepslate", "natural_stone", "stone"],
  "deepslate_bricks": ["deepslate", "masonry", "stone"],
  "deepslate_tiles": ["deepslate", "masonry", "stone"],
  "diamond_block": ["metal_and_ore"],
  "diorite": ["natural_stone", "stone"],
  "dirt": ["earth"],
  "dripstone_block": ["natural_stone", "stone"],
  "emerald_block": ["metal_and_ore"],
  "end_stone": ["end", "stone"],
  "end_stone_bricks": ["end", "masonry", "stone"],
  "gilded_blackstone": ["blackstone", "masonry", "nether", "stone"],
  "glowstone": ["luminant_and_special"],
  "gold_block": ["metal_and_ore"],
  "granite": ["natural_stone", "stone"],
  "gravel": ["earth"],
  "gray_concrete": ["concrete"],
  "gray_concrete_powder": ["concrete"],
  "gray_glazed_terracotta": ["terracotta"],
  "gray_terracotta": ["terracotta"],
  "gray_wool": ["wool_and_carpet"],
  "green_concrete": ["concrete"],
  "green_concrete_powder": ["concrete"],
  "green_glazed_terracotta": ["terracotta"],
  "green_terracotta": ["terracotta"],
  "green_wool": ["wool_and_carpet"],
  "honeycomb_block": ["organics"],
  "iron_block": ["metal_and_ore"],
  "jungle_log": ["wood"],
  "jungle_log_top": ["wood"],
  "jungle_planks": ["wood"],
  "lapis_block": ["metal_and_ore"],
  "light_blue_concrete": ["concrete"],
  "light_blue_concrete_powder": ["concrete"],
  "light_blue_glazed_terracotta": ["terracotta"],
  "light_blue_terracotta": ["terracotta"],
  "light_blue_wool": ["wool_and_carpet"],
  "light_gray_concrete": ["concrete"],
  "light_gray_concrete_powder": ["concrete"],
  "light_gray_glazed_terracotta": ["terracotta"],
  "light_gray_terracotta": ["terracotta"],
  "light_gray_wool": ["wool_and_carpet"],
  "lime_concrete": ["concrete"],
  "lime_concrete_powder": ["concrete"],
  "lime_glazed_terracotta": ["terracotta"],
  "lime_terracotta": ["terracotta"],
  "lime_wool": ["wool_and_carpet"],
  "magenta_concrete": ["concrete"],
  "magenta_concrete_powder": ["concrete"],
  "magenta_glazed_terracotta": ["terracotta"],
  "magenta_terracotta": ["terracotta"],
  "magenta_wool": ["wool_and_carpet"],
  "mangrove_log": ["wood"],
  "mangrove_log_top": ["wood"],
  "mangrove_planks": ["wood"],
  "moss_block": ["organics"],
  "mossy_cobblestone": ["organics", "stone"],
  "mossy_stone_bricks": ["masonry", "organics", "stone"],
  "mud": ["earth"],
  "mud_bricks": ["earth", "masonry", "stone"],
  "nether_bricks": ["masonry", "nether", "nether_brick", "stone"],
  "nether_wart_block": ["nether", "organics"],
  "netherite_block": ["metal_and_ore", "nether"],
  "netherrack": ["nether"],
  "note_block": ["wood"],
  "oak_log": ["wood"],
  "oak_log_top": ["wood"],
  "oak_planks": ["wood"],
  "obsidian": ["end", "stone"],
  "orange_concrete": ["concrete"],
  "orange_concrete_powder": ["concrete"],
  "orange_glazed_terracotta": ["terracotta"],
  "orange_terracotta": ["terracotta"],
  "orange_wool": ["wool_and_carpet"],
  "packed_mud": ["earth"],
  "pale_moss_block": ["organics"],
  "pale_moss_carpet": ["organics", "wool_and_carpet"],
  "pale_oak_log": ["wood"],
  "pale_oak_log_top": ["wood"],
  "pale_oak_planks": ["wood"],
  "pink_concrete": ["concrete"],
  "pink_concrete_powder": ["concrete"],
  "pink_glazed_terracotta": ["terracotta"],
  "pink_terracotta": ["terracotta"],
  "pink_wool": ["wool_and_carpet"],
  "polished_andesite": ["masonry", "stone"],
  "polished_blackstone": ["blackstone", "masonry", "stone"],
  "polished_blackstone_bricks": ["blackstone", "masonry", "stone"],
  "polished_deepslate": ["deepslate", "masonry", "stone"],
  "polished_diorite": ["masonry", "stone"],
  "polished_granite": ["masonry", "stone"],
  "polished_tuff": ["masonry", "stone", "tuff"],
  "prismarine_bricks": ["masonry", "prismarine", "stone"],
  "purple_concrete": ["concrete"],
  "purple_concrete_powder": ["concrete"],
  "purple_glazed_terracotta": ["terracotta"],
  "purple_terracotta": ["terracotta"],
  "purple_wool": ["wool_and_carpet"],
  "purpur_block": ["end", "stone"],
  "purpur_pillar": ["end", "stone"],
  "purpur_pillar_top": ["end", "stone"],
  "quartz_bricks": ["masonry", "quartz", "stone"],
  "quartz_pillar": ["masonry", "quartz", "stone"],
  "quartz_pillar_top": ["masonry", "quartz", "stone"],
  "red_concrete": ["concrete"],
  "red_concrete_powder": ["concrete"],
  "red_glazed_terracotta": ["terracotta"],
  "red_nether_bricks": ["masonry", "nether", "nether_brick", "stone"],
  "red_sand": ["earth"],
  "red_terracotta": ["terracotta"],
  "red_wool": ["wool_and_carpet"],
  "redstone_block": ["metal_and_ore"],
  "redstone_lamp": ["luminant_and_special"],
  "resin_block": ["resin", "stone"],
  "resin_bricks": ["masonry", "resin", "stone"],
  "sand": ["earth"],
  "shroomlight": ["luminant_and_special", "nether"],
  "smooth_basalt": ["natural_stone", "stone"],
  "smooth_stone": ["masonry", "stone"],
  "snow": ["earth"],
  "soul_sand": ["earth", "nether"],
  "soul_soil": ["earth", "nether"],
  "sponge": ["organics"],
  "spruce_log": ["wood"],
  "spruce_log_top": ["wood"],
  "spruce_planks": ["wood"],
  "stone": ["natural_stone", "stone"],
  "stone_bricks": ["masonry", "stone"],
  "stripped_acacia_log": ["wood"],
  "stripped_acacia_log_top": ["wood"],
  "stripped_bamboo_block": ["bamboo", "wood"],
  "stripped_birch_log": ["wood"],
  "stripped_birch_log_top": ["wood"],
  "stripped_cherry_log": ["wood"],
  "stripped_cherry_log_top": ["wood"],
  "stripped_dark_oak_log": ["wood"],
  "stripped_dark_oak_log_top": ["wood"],
  "stripped_jungle_log": ["wood"],
  "stripped_jungle_log_top": ["wood"],
  "stripped_mangrove_log": ["wood"],
  "stripped_mangrove_log_top": ["wood"],
  "stripped_oak_log": ["wood"],
  "stripped_oak_log_top": ["wood"],
  "stripped_pale_oak_log": ["wood"],
  "stripped_pale_oak_log_top": ["wood"],
  "stripped_spruce_log": ["wood"],
  "stripped_spruce_log_top": ["wood"],
  "terracotta": ["terracotta"],
  "tuff": ["natural_stone", "stone", "tuff"],
  "tuff_bricks": ["masonry", "stone", "tuff"],
  "warped_nylium": ["nether", "organics"],
  "warped_planks": ["nether", "nether_wood", "wood"],
  "warped_wart_block": ["nether", "organics"],
  "white_concrete": ["concrete"],
  "white_concrete_powder": ["concrete"],
  "white_glazed_terracotta": ["terracotta"],
  "white_terracotta": ["terracotta"],
  "white_wool": ["wool_and_carpet"],
  "yellow_concrete": ["concrete"],
  "yellow_concrete_powder": ["concrete"],
  "yellow_glazed_terracotta": ["terracotta"],
  "yellow_terracotta": ["terracotta"],
  "yellow_wool": ["wool_and_carpet"],
};