import type { BlockId } from "../types/blockId";

export const BLOCK_NAMES: Record<BlockId, string> = {
  acacia_log: "Acacia Log",
  acacia_log_top: "Acacia Log Top",
  acacia_planks: "Acacia Planks",
  andesite: "Andesite",
  bamboo_block: "Bamboo Block",
  bamboo_mosaic: "Bamboo Mosaic",
  bamboo_planks: "Bamboo Planks",
  birch_log: "Birch Log",
  birch_log_top: "Birch Log Top",
  birch_planks: "Birch Planks",
  black_concrete: "Black Concrete",
  black_concrete_powder: "Black Concrete Powder",
  black_glazed_terracotta: "Black Glazed Terracotta",
  black_terracotta: "Black Terracotta",
  black_wool: "Black Wool",
  blackstone: "Blackstone",
  blue_concrete: "Blue Concrete",
  blue_concrete_powder: "Blue Concrete Powder",
  blue_glazed_terracotta: "Blue Glazed Terracotta",
  blue_terracotta: "Blue Terracotta",
  blue_wool: "Blue Wool",
  bricks: "Bricks",
  brown_concrete: "Brown Concrete",
  brown_concrete_powder: "Brown Concrete Powder",
  brown_glazed_terracotta: "Brown Glazed Terracotta",
  brown_terracotta: "Brown Terracotta",
  brown_wool: "Brown Wool",
  calcite: "Calcite",
  cherry_log: "Cherry Log",
  cherry_log_top: "Cherry Log Top",
  cherry_planks: "Cherry Planks",
  chiseled_deepslate: "Chiseled Deepslate",
  chiseled_nether_bricks: "Chiseled Nether Bricks",
  chiseled_polished_blackstone: "Chiseled Polished Blackstone",
  chiseled_quartz_block: "Chiseled Quartz Block",
  chiseled_resin_bricks: "Chiseled Resin Bricks",
  chiseled_stone_bricks: "Chiseled Stone Bricks",
  chiseled_tuff: "Chiseled Tuff",
  chiseled_tuff_bricks: "Chiseled Tuff Bricks",
  clay: "Clay",
  coal_block: "Coal Block",
  cobbled_deepslate: "Cobbled Deepslate",
  cobblestone: "Cobblestone",
  cracked_deepslate_bricks: "Cracked Deepslate Bricks",
  cracked_deepslate_tiles: "Cracked Deepslate Tiles",
  cracked_nether_bricks: "Cracked Nether Bricks",
  cracked_polished_blackstone_bricks: "Cracked Polished Blackstone Bricks",
  cracked_stone_bricks: "Cracked Stone Bricks",
  creaking_heart: "Creaking Heart",
  crimson_nylium: "Crimson Nylium",
  crimson_planks: "Crimson Planks",
  cyan_concrete: "Cyan Concrete",
  cyan_concrete_powder: "Cyan Concrete Powder",
  cyan_glazed_terracotta: "Cyan Glazed Terracotta",
  cyan_terracotta: "Cyan Terracotta",
  cyan_wool: "Cyan Wool",
  dark_oak_log: "Dark Oak Log",
  dark_oak_log_top: "Dark Oak Log Top",
  dark_oak_planks: "Dark Oak Planks",
  dark_prismarine: "Dark Prismarine",
  deepslate: "Deepslate",
  deepslate_bricks: "Deepslate Bricks",
  deepslate_tiles: "Deepslate Tiles",
  diamond_block: "Diamond Block",
  diorite: "Diorite",
  dirt: "Dirt",
  dripstone_block: "Dripstone Block",
  emerald_block: "Emerald Block",
  end_stone: "End Stone",
  end_stone_bricks: "End Stone Bricks",
  gilded_blackstone: "Gilded Blackstone",
  glowstone: "Glowstone",
  gold_block: "Gold Block",
  granite: "Granite",
  gravel: "Gravel",
  gray_concrete: "Gray Concrete",
  gray_concrete_powder: "Gray Concrete Powder",
  gray_glazed_terracotta: "Gray Glazed Terracotta",
  gray_terracotta: "Gray Terracotta",
  gray_wool: "Gray Wool",
  green_concrete: "Green Concrete",
  green_concrete_powder: "Green Concrete Powder",
  green_glazed_terracotta: "Green Glazed Terracotta",
  green_terracotta: "Green Terracotta",
  green_wool: "Green Wool",
  honeycomb_block: "Honeycomb Block",
  iron_block: "Iron Block",
  jungle_log: "Jungle Log",
  jungle_log_top: "Jungle Log Top",
  jungle_planks: "Jungle Planks",
  lapis_block: "Lapis Block",
  light_blue_concrete: "Light Blue Concrete",
  light_blue_concrete_powder: "Light Blue Concrete Powder",
  light_blue_glazed_terracotta: "Light Blue Glazed Terracotta",
  light_blue_terracotta: "Light Blue Terracotta",
  light_blue_wool: "Light Blue Wool",
  light_gray_concrete: "Light Gray Concrete",
  light_gray_concrete_powder: "Light Gray Concrete Powder",
  light_gray_glazed_terracotta: "Light Gray Glazed Terracotta",
  light_gray_terracotta: "Light Gray Terracotta",
  light_gray_wool: "Light Gray Wool",
  lime_concrete: "Lime Concrete",
  lime_concrete_powder: "Lime Concrete Powder",
  lime_glazed_terracotta: "Lime Glazed Terracotta",
  lime_terracotta: "Lime Terracotta",
  lime_wool: "Lime Wool",
  magenta_concrete: "Magenta Concrete",
  magenta_concrete_powder: "Magenta Concrete Powder",
  magenta_glazed_terracotta: "Magenta Glazed Terracotta",
  magenta_terracotta: "Magenta Terracotta",
  magenta_wool: "Magenta Wool",
  mangrove_log: "Mangrove Log",
  mangrove_log_top: "Mangrove Log Top",
  mangrove_planks: "Mangrove Planks",
  moss_block: "Moss Block",
  mossy_cobblestone: "Mossy Cobblestone",
  mossy_stone_bricks: "Mossy Stone Bricks",
  mud: "Mud",
  mud_bricks: "Mud Bricks",
  nether_bricks: "Nether Bricks",
  nether_wart_block: "Nether Wart Block",
  netherite_block: "Netherite Block",
  netherrack: "Netherrack",
  note_block: "Note Block",
  oak_log: "Oak Log",
  oak_log_top: "Oak Log Top",
  oak_planks: "Oak Planks",
  obsidian: "Obsidian",
  orange_concrete: "Orange Concrete",
  orange_concrete_powder: "Orange Concrete Powder",
  orange_glazed_terracotta: "Orange Glazed Terracotta",
  orange_terracotta: "Orange Terracotta",
  orange_wool: "Orange Wool",
  packed_mud: "Packed Mud",
  pale_moss_block: "Pale Moss Block",
  pale_moss_carpet: "Pale Moss Carpet",
  pale_oak_log: "Pale Oak Log",
  pale_oak_log_top: "Pale Oak Log Top",
  pale_oak_planks: "Pale Oak Planks",
  pink_concrete: "Pink Concrete",
  pink_concrete_powder: "Pink Concrete Powder",
  pink_glazed_terracotta: "Pink Glazed Terracotta",
  pink_terracotta: "Pink Terracotta",
  pink_wool: "Pink Wool",
  polished_andesite: "Polished Andesite",
  polished_blackstone: "Polished Blackstone",
  polished_blackstone_bricks: "Polished Blackstone Bricks",
  polished_deepslate: "Polished Deepslate",
  polished_diorite: "Polished Diorite",
  polished_granite: "Polished Granite",
  polished_tuff: "Polished Tuff",
  prismarine_bricks: "Prismarine Bricks",
  purple_concrete: "Purple Concrete",
  purple_concrete_powder: "Purple Concrete Powder",
  purple_glazed_terracotta: "Purple Glazed Terracotta",
  purple_terracotta: "Purple Terracotta",
  purple_wool: "Purple Wool",
  purpur_block: "Purpur Block",
  purpur_pillar: "Purpur Pillar",
  purpur_pillar_top: "Purpur Pillar Top",
  quartz_bricks: "Quartz Bricks",
  quartz_pillar: "Quartz Pillar",
  quartz_pillar_top: "Quartz Pillar Top",
  red_concrete: "Red Concrete",
  red_concrete_powder: "Red Concrete Powder",
  red_glazed_terracotta: "Red Glazed Terracotta",
  red_nether_bricks: "Red Nether Bricks",
  red_sand: "Red Sand",
  red_terracotta: "Red Terracotta",
  red_wool: "Red Wool",
  redstone_block: "Redstone Block",
  redstone_lamp: "Redstone Lamp",
  resin_block: "Resin Block",
  resin_bricks: "Resin Bricks",
  sand: "Sand",
  shroomlight: "Shroomlight",
  smooth_basalt: "Smooth Basalt",
  smooth_stone: "Smooth Stone",
  snow: "Snow",
  soul_sand: "Soul Sand",
  soul_soil: "Soul Soil",
  sponge: "Sponge",
  spruce_log: "Spruce Log",
  spruce_log_top: "Spruce Log Top",
  spruce_planks: "Spruce Planks",
  stone: "Stone",
  stone_bricks: "Stone Bricks",
  stripped_acacia_log: "Stripped Acacia Log",
  stripped_acacia_log_top: "Stripped Acacia Log Top",
  stripped_bamboo_block: "Stripped Bamboo Block",
  stripped_birch_log: "Stripped Birch Log",
  stripped_birch_log_top: "Stripped Birch Log Top",
  stripped_cherry_log: "Stripped Cherry Log",
  stripped_cherry_log_top: "Stripped Cherry Log Top",
  stripped_dark_oak_log: "Stripped Dark Oak Log",
  stripped_dark_oak_log_top: "Stripped Dark Oak Log Top",
  stripped_jungle_log: "Stripped Jungle Log",
  stripped_jungle_log_top: "Stripped Jungle Log Top",
  stripped_mangrove_log: "Stripped Mangrove Log",
  stripped_mangrove_log_top: "Stripped Mangrove Log Top",
  stripped_oak_log: "Stripped Oak Log",
  stripped_oak_log_top: "Stripped Oak Log Top",
  stripped_pale_oak_log: "Stripped Pale Oak Log",
  stripped_pale_oak_log_top: "Stripped Pale Oak Log Top",
  stripped_spruce_log: "Stripped Spruce Log",
  stripped_spruce_log_top: "Stripped Spruce Log Top",
  terracotta: "Terracotta",
  tuff: "Tuff",
  tuff_bricks: "Tuff Bricks",
  warped_nylium: "Warped Nylium",
  warped_planks: "Warped Planks",
  warped_wart_block: "Warped Wart Block",
  white_concrete: "White Concrete",
  white_concrete_powder: "White Concrete Powder",
  white_glazed_terracotta: "White Glazed Terracotta",
  white_terracotta: "White Terracotta",
  white_wool: "White Wool",
  yellow_concrete: "Yellow Concrete",
  yellow_concrete_powder: "Yellow Concrete Powder",
  yellow_glazed_terracotta: "Yellow Glazed Terracotta",
  yellow_terracotta: "Yellow Terracotta",
  yellow_wool: "Yellow Wool",
};
