

export const IMAGE_BLUEPRINT_MOBILE_BG_DISPLAY_RADIUS = 3;
export const IMAGE_BLUEPRINT_WEB_BG_DISPLAY_RADIUS = 5;
export const IMAGE_BLUEPRINT_WEB_VERBOSE_WIDTH = 120;
export const IMAGE_BLUEPRINT_WEB_FONT_SIZE = 12;
export const IMAGE_BLUEPRINT_WEB_LINE_HEIGHT = 16;
export const IMAGE_BLUEPRINT_MOBILE_VERBOSE_WIDTH = 80;
export const IMAGE_BLUEPRINT_MOBILE_FONT_SIZE = 8;
export const IMAGE_BLUEPRINT_MOBILE_LINE_HEIGHT = 11;